# Generated by Django 5.2.4 on 2025-08-08 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_name_project_account_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(default='Manual Entry', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 8, 3, 24, 30, 63728, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
